services:
  - type: web
    name: meet
    env: node
    region: oregon  # ou frankfurt, singapore selon votre localisation
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Render utilise généralement le port 10000
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

